#!/usr/bin/env python3
"""
run_project.py

Cross-platform reproducibility entry point for the League of Legends project.

This runner intentionally uses Python subprocess calls rather than PowerShell,
Bash-specific syntax, or platform-specific path separators. It should work on
Windows, Linux, and macOS as long as Python >= 3.10 and the dependencies in
requirements.txt are installed.

Current supported pipeline:
    q1  - Temporal behavior and subsequent ranked performance

Examples
--------
Check that the environment, scripts, and required data exist:

    python run_project.py q1 --check-only

Reproduce Question 1 from the already-processed tracked-player data:

    python run_project.py q1 --start-at 3

Re-run only the analysis stages from the existing timeline tables:

    python run_project.py q1 --start-at 6

Dry-run to print the commands without executing them:

    python run_project.py q1 --start-at 3 --dry-run

Notes
-----
Stages 00-02 depend on the original raw dataset and crawler provenance files.
They remain in code/ for full reproducibility, but the recommended submission
reproduction path begins at stage 03 because the repository already contains
the canonical processed Parquet tables and tracked-player cohort lookups.
"""

from __future__ import annotations

import argparse
import importlib
import shlex
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CODE = ROOT / "code"
DATA = ROOT / "data"

REQUIRED_PACKAGES = {
    "numpy": "numpy",
    "pandas": "pandas",
    "pyarrow": "pyarrow",
    "duckdb": "duckdb",
    "matplotlib": "matplotlib",
    "sklearn": "scikit-learn",
}

Q1_SCRIPTS = {
    3: CODE / "03_audit_tracking_coverage.py",
    4: CODE / "04_audit_dataset.py",
    5: CODE / "05_build_player_timelines.py",
    6: CODE / "06_exploratory_analysis.py",
    7: CODE / "07_statistical_analysis.py",
    8: CODE / "08_predictive_modeling.py",
    9: CODE / "09_q1_robustness.py",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Cross-platform project reproduction runner."
    )
    sub = parser.add_subparsers(dest="pipeline", required=True)

    q1 = sub.add_parser(
        "q1",
        help="Reproduce Question 1 (temporal behavior -> next-match performance).",
    )
    q1.add_argument(
        "--start-at",
        type=int,
        choices=range(3, 10),
        default=3,
        metavar="STAGE",
        help="First stage to run (3-9). Default: 3.",
    )
    q1.add_argument(
        "--stop-after",
        type=int,
        choices=range(3, 10),
        default=9,
        metavar="STAGE",
        help="Last stage to run (3-9). Default: 9.",
    )
    q1.add_argument(
        "--check-only",
        action="store_true",
        help="Validate Python, packages, scripts, and required inputs; run nothing.",
    )
    q1.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the commands that would run without executing them.",
    )
    q1.add_argument(
        "--no-overwrite",
        action="store_true",
        help="Do not pass --overwrite to stage scripts.",
    )
    return parser.parse_args()


def check_python() -> list[str]:
    problems = []
    if sys.version_info < (3, 10):
        problems.append(
            f"Python >= 3.10 is required; found {sys.version.split()[0]}."
        )
    return problems


def check_packages() -> list[str]:
    problems = []
    for import_name, install_name in REQUIRED_PACKAGES.items():
        try:
            importlib.import_module(import_name)
        except Exception as exc:
            problems.append(
                f"Missing/unusable package '{install_name}' "
                f"(import {import_name!r} failed: {exc})."
            )
    return problems


def check_scripts(start: int, stop: int) -> list[str]:
    problems = []
    for stage in range(start, stop + 1):
        path = Q1_SCRIPTS[stage]
        if not path.exists():
            problems.append(f"Missing stage {stage:02d} script: {path}")
    return problems


def has_parquet_files(path: Path) -> bool:
    return path.exists() and any(path.rglob("*.parquet"))


def check_inputs(start: int) -> list[str]:
    """
    Validate the earliest-stage inputs required for the requested starting point.
    Later stages are generated by earlier ones during a full run.
    """
    problems = []

    processed_roots = [
        DATA / "processed" / "full_na",
        DATA / "processed" / "full_kr",
        DATA / "processed" / "full_eu",
    ]

    if start <= 5:
        for path in processed_roots:
            if not has_parquet_files(path):
                problems.append(f"Missing canonical processed Parquet data: {path}")

    if start <= 3:
        for cohort in ("authoritative", "alias_confirmed"):
            for source in ("NA", "KR", "EU"):
                path = (
                    DATA
                    / "processed"
                    / "tracking"
                    / cohort
                    / source
                    / "tracked_players.parquet"
                )
                if not path.exists():
                    problems.append(f"Missing tracked-player lookup: {path}")

    if start == 4:
        linked = (
            DATA
            / "processed"
            / "tracking"
            / "linked"
            / "authoritative"
        )
        if not has_parquet_files(linked):
            problems.append(
                "Stage 04 requires existing authoritative linked Parquet data. "
                "Run from stage 03 or restore data/processed/tracking/linked."
            )

    if start == 5:
        linked = (
            DATA
            / "processed"
            / "tracking"
            / "linked"
            / "authoritative"
        )
        if not has_parquet_files(linked):
            problems.append(
                "Stage 05 requires existing authoritative linked Parquet data."
            )

    if start >= 6:
        timelines = DATA / "analysis" / "timelines" / "solo420_targets"
        if not has_parquet_files(timelines):
            problems.append(
                f"Stage {start:02d} requires existing timeline Parquet data: "
                f"{timelines}"
            )

    if start == 9:
        stats = DATA / "analysis" / "statistics" / "tables" / "behavior_effects.csv"
        if not stats.exists():
            problems.append(
                "Stage 09 requires stage-07 statistical outputs "
                "(data/analysis/statistics/tables/behavior_effects.csv)."
            )

    return problems


def q1_commands(overwrite: bool) -> dict[int, list[str]]:
    processed = [
        f"NA={DATA / 'processed' / 'full_na'}",
        f"KR={DATA / 'processed' / 'full_kr'}",
        f"EU={DATA / 'processed' / 'full_eu'}",
    ]

    tracking_root = DATA / "processed" / "tracking"
    linked_authoritative = tracking_root / "linked" / "authoritative"
    timelines_root = DATA / "analysis" / "timelines"
    solo_targets = timelines_root / "solo420_targets"

    commands = {
        3: [
            sys.executable,
            str(Q1_SCRIPTS[3]),
            "--processed",
            *processed,
            "--tracking",
            str(tracking_root),
            "--output",
            str(tracking_root / "coverage_audit"),
            "--linked-output",
            str(tracking_root / "linked"),
        ],
        4: [
            sys.executable,
            str(Q1_SCRIPTS[4]),
            "--processed",
            *processed,
            "--linked",
            str(linked_authoritative),
            "--output",
            str(DATA / "processed" / "analysis_audit"),
        ],
        5: [
            sys.executable,
            str(Q1_SCRIPTS[5]),
            "--processed",
            *processed,
            "--linked",
            str(linked_authoritative),
            "--output",
            str(timelines_root),
        ],
        6: [
            sys.executable,
            str(Q1_SCRIPTS[6]),
            "--timelines",
            str(solo_targets),
            "--output",
            str(DATA / "analysis" / "eda"),
        ],
        7: [
            sys.executable,
            str(Q1_SCRIPTS[7]),
            "--timelines",
            str(solo_targets),
            "--output",
            str(DATA / "analysis" / "statistics"),
        ],
        8: [
            sys.executable,
            str(Q1_SCRIPTS[8]),
            "--timelines",
            str(solo_targets),
            "--output",
            str(DATA / "analysis" / "prediction"),
        ],
        9: [
            sys.executable,
            str(Q1_SCRIPTS[9]),
            "--timelines",
            str(solo_targets),
            "--statistics",
            str(DATA / "analysis" / "statistics"),
            "--output",
            str(DATA / "analysis" / "q1_robustness"),
        ],
    }

    if overwrite:
        for command in commands.values():
            command.append("--overwrite")

    return commands


def run_q1(args: argparse.Namespace) -> int:
    if args.start_at > args.stop_after:
        raise SystemExit("--start-at must be <= --stop-after.")

    problems = []
    problems.extend(check_python())
    problems.extend(check_packages())
    problems.extend(check_scripts(args.start_at, args.stop_after))
    problems.extend(check_inputs(args.start_at))

    print(f"Project root: {ROOT}")
    print(f"Python:       {sys.executable}")
    print(f"Version:      {sys.version.split()[0]}")
    print(
        f"Q1 stages:    {args.start_at:02d} -> {args.stop_after:02d}"
    )

    if problems:
        print("\nENVIRONMENT / INPUT CHECK FAILED:")
        for problem in problems:
            print(f"  - {problem}")
        print(
            "\nInstall dependencies with:\n"
            "  python -m pip install -r requirements.txt"
        )
        return 1

    print("\nEnvironment and required inputs: OK")

    if args.check_only:
        return 0

    commands = q1_commands(overwrite=not args.no_overwrite)

    for stage in range(args.start_at, args.stop_after + 1):
        command = commands[stage]
        print(f"\n=== Stage {stage:02d}: {Q1_SCRIPTS[stage].name} ===")
        print(shlex.join(command))

        if args.dry_run:
            continue

        subprocess.run(
            command,
            cwd=ROOT,
            check=True,
        )

    print("\nQ1 reproduction pipeline completed successfully.")
    return 0


def main() -> int:
    args = parse_args()

    if args.pipeline == "q1":
        return run_q1(args)

    raise SystemExit(f"Unsupported pipeline: {args.pipeline}")


if __name__ == "__main__":
    raise SystemExit(main())
