#!/usr/bin/env python3
"""Interactive Streamlit demo for the final League of Legends project.

The app reads the compact outputs generated by the analysis pipeline. It does
not retrain models or rescan the full match corpus, so it stays fast and safe
for a live presentation.

Run from the project root after generating results:

    python code/run_project.py
    streamlit run demo/app.py
"""
from __future__ import annotations

import io
import json
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "data" / "analysis"

Q1_TABLES = ANALYSIS / "q1" / "tables"
Q1_FIGURES = ANALYSIS / "q1" / "figures" / "report"
Q2_TABLES = ANALYSIS / "q2" / "tables"
Q3_TABLES = ANALYSIS / "q3" / "tables"
Q3_FIGURES = ANALYSIS / "q3" / "figures" / "report"

PROJECT_MATCHES = 497_102
PROJECT_PARTICIPANTS = 4_971_020
PROJECT_REGIONS = 3
TRACKED_PLAYERS = 11_169
MIN_PAIR_GAMES = 500
MIN_PERFORMANCE_GAMES = 1_000

REGION_COLORS = {
    "NA": "#4C9AFF",
    "KR": "#E66A6A",
    "EU": "#D8B45A",
}


st.set_page_config(
    page_title="Finding the Needle in Ranked Play",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
    <style>
    .block-container {padding-top: 1.5rem; padding-bottom: 2rem;}
    h1, h2, h3 {letter-spacing: -0.02em;}
    .hero {
        padding: 1.25rem 1.4rem;
        border: 1px solid rgba(200,155,60,.35);
        border-radius: 16px;
        background: linear-gradient(135deg, rgba(15,36,56,.92), rgba(8,22,36,.96));
        margin-bottom: 1rem;
    }
    .hero-title {
        color: #F5E6C8;
        font-size: 2rem;
        font-weight: 750;
        line-height: 1.05;
        margin-bottom: .25rem;
    }
    .hero-sub {
        color: #C89B3C;
        font-size: 1.02rem;
        font-weight: 600;
    }
    .problem-card {
        border: 1px solid rgba(200,155,60,.28);
        border-radius: 14px;
        padding: 1rem 1.05rem;
        background: rgba(15,36,56,.52);
        min-height: 175px;
    }
    .problem-card h4 {
        color: #E6C77A;
        margin: 0 0 .5rem 0;
        font-size: 1.02rem;
    }
    .small-note {
        color: #AEBAC6;
        font-size: .90rem;
    }
    .status-ok {color: #79D69B; font-weight: 650;}
    .status-missing {color: #F1B17A; font-weight: 650;}
    div[data-testid="stMetric"] {
        border: 1px solid rgba(200,155,60,.22);
        border-radius: 12px;
        padding: .55rem .7rem;
        background: rgba(15,36,56,.35);
    }
    </style>
    """,
    unsafe_allow_html=True,
)


@st.cache_data(show_spinner=False)
def read_csv(path: Path) -> pd.DataFrame:
    """Load one generated CSV while preserving the literal region label "NA"."""
    # Pandas treats the string "NA" as missing by default; preserving it fixes
    # the empty North-America plots in the Problem 1 region selector.
    return pd.read_csv(path, keep_default_na=False, na_values=[""])


@st.cache_data(show_spinner=False)
def report_image_bytes(path: Path, background: str = "#F7F3E8") -> bytes:
    """Flatten a transparent report PNG onto a light background for readability."""
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
        bg = Image.new("RGBA", rgba.size, background)
        bg.alpha_composite(rgba)
        flattened = bg.convert("RGB")

        buffer = io.BytesIO()
        flattened.save(buffer, format="PNG")
        return buffer.getvalue()


@st.cache_data(show_spinner=False)
def read_json(path: Path) -> dict:
    """Load one generated JSON summary and cache it for the current session."""
    return json.loads(path.read_text(encoding="utf-8"))


def file_ready(path: Path) -> bool:
    """Return whether a required generated output currently exists."""
    return path.exists() and path.is_file()


def format_integer(value: float | int) -> str:
    """Format whole-number metrics with thousands separators."""
    return f"{int(round(float(value))):,}"


def format_decimal(value: float, digits: int = 4) -> str:
    """Format a numeric result consistently for metric cards."""
    return f"{float(value):.{digits}f}"


def key_metric(table: pd.DataFrame, name: str) -> float | None:
    """Read one named metric from Q1's compact key-results table."""
    if table.empty or "metric" not in table or "value" not in table:
        return None
    rows = table.loc[table["metric"] == name, "value"]
    return None if rows.empty else float(rows.iloc[0])


def clean_effect_term(term: str) -> str:
    """Convert internal regression term names into short presentation labels."""
    text = str(term)
    replacements = {
        "session_depth_": "Session game ",
        "post_loss_gap_": "Gap ",
        "recent_games_": "Recent games ",
    }
    for prefix, replacement in replacements.items():
        if text.startswith(prefix):
            return text.replace(prefix, replacement, 1)
    return text.replace("_", " ").title()


def style_plot(fig: go.Figure, *, height: int = 470) -> go.Figure:
    """Apply one consistent dark navy/gold visual style to interactive charts."""
    fig.update_layout(
        template="plotly_dark",
        height=height,
        margin=dict(l=20, r=20, t=55, b=20),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(8,22,36,0.35)",
        font=dict(color="#E8EDF2"),
        title_font=dict(color="#F5E6C8"),
        legend_title_text="",
    )
    return fig


def missing_results_message(problem: str, command: str) -> None:
    """Show a concise recovery message when generated demo inputs are absent."""
    st.warning(
        f"{problem} outputs are not available yet. Generate them first with:"
    )
    st.code(command, language="bash")


def pairs_for_champion(pairs: pd.DataFrame, champion: str) -> pd.DataFrame:
    """Return all pair rows involving one champion with a unified partner column."""
    mask = (pairs["champion_a"] == champion) | (pairs["champion_b"] == champion)
    out = pairs.loc[mask].copy()
    out["partner"] = np.where(
        out["champion_a"] == champion,
        out["champion_b"],
        out["champion_a"],
    )
    return out


def primary_effects(effects: pd.DataFrame, hypothesis: str) -> pd.DataFrame:
    """Select the primary adjusted coefficient family for one Q1 hypothesis."""
    settings = {
        "Session depth": ("H1_session_depth", "30m_session_boundary"),
        "Post-loss requeue": ("H2_post_loss_requeue", "categorical_requeue_gap"),
        "Recent ranked volume": ("H3_recent_volume", "6h_window"),
    }
    internal_hypothesis, setting = settings[hypothesis]
    return effects[
        (effects["hypothesis"] == internal_hypothesis)
        & (effects["specification"] == "adjusted")
        & (effects["parameter_setting"] == setting)
    ].copy()


def q1_effect_figure(data: pd.DataFrame, hypothesis: str, region: str) -> go.Figure:
    """Build an interactive coefficient-and-confidence-interval view for Q1."""
    sub = data if region == "ALL" else data[data["source"] == region]
    fig = go.Figure()

    for source in ["NA", "KR", "EU"]:
        current = sub[sub["source"] == source].copy()
        if current.empty:
            continue
        current["label"] = current["term"].map(clean_effect_term)
        current = current.sort_values("estimate_percentage_points")

        estimate = current["estimate_percentage_points"].astype(float)
        low = current["ci_low_percentage_points"].astype(float)
        high = current["ci_high_percentage_points"].astype(float)

        fig.add_trace(
            go.Scatter(
                x=estimate,
                y=current["label"],
                mode="markers",
                name=source,
                marker=dict(size=9, color=REGION_COLORS[source]),
                error_x=dict(
                    type="data",
                    symmetric=False,
                    array=(high - estimate),
                    arrayminus=(estimate - low),
                    thickness=1.4,
                ),
                customdata=np.column_stack(
                    [
                        current["p_value_holm"].astype(float),
                        current["reference_category"].astype(str),
                    ]
                ),
                hovertemplate=(
                    "<b>%{y}</b><br>"
                    "Effect: %{x:.3f} pp<br>"
                    "Holm p: %{customdata[0]:.4g}<br>"
                    "Reference: %{customdata[1]}<extra>%{fullData.name}</extra>"
                ),
            )
        )

    fig.add_vline(x=0, line_dash="dash", line_color="#AAB5BF")
    fig.update_layout(
        title=f"{hypothesis}: adjusted within-player effects",
        xaxis_title="Change in next-match win probability (percentage points)",
        yaxis_title="",
    )
    return style_plot(fig, height=500)


def q2_scatter(data: pd.DataFrame, champion: str) -> go.Figure:
    """Plot one champion's supported pairings by association and win surplus."""
    shown = data[data["games_together"] >= MIN_PAIR_GAMES].copy()
    fig = px.scatter(
        shown,
        x="association",
        y="win_surplus_pp",
        size="games_together",
        hover_name="partner",
        hover_data={
            "games_together": ":,",
            "pair_win_rate": ":.3f",
            "association": ":.3f",
            "win_surplus_pp": ":.3f",
        },
        size_max=34,
        color="games_together",
        color_continuous_scale=["#37506A", "#C89B3C", "#F4D98A"],
        labels={
            "association": "Normalized association: log₂(lift)",
            "win_surplus_pp": "Pair win surplus (pp)",
            "games_together": "Games together",
        },
        title=f"{champion}: association vs. descriptive pair performance",
    )
    fig.add_hline(y=0, line_dash="dash", line_color="#AAB5BF")
    fig.add_vline(x=0, line_dash="dash", line_color="#AAB5BF")
    return style_plot(fig, height=520)


def pagerank_figure(centrality: pd.DataFrame, selected: str) -> go.Figure:
    """Show the most central champions and visually mark the current selection."""
    top = centrality.nlargest(15, "pagerank_association").sort_values(
        "pagerank_association"
    )
    colors = [
        "#F4D98A" if name == selected else "#4B6D8C"
        for name in top["champion_name"]
    ]
    fig = go.Figure(
        go.Bar(
            x=top["pagerank_association"],
            y=top["champion_name"],
            orientation="h",
            marker_color=colors,
            hovertemplate="<b>%{y}</b><br>PageRank: %{x:.5f}<extra></extra>",
        )
    )
    fig.update_layout(
        title="Most central champions in the normalized association network",
        xaxis_title="Association-weighted PageRank",
        yaxis_title="",
    )
    return style_plot(fig, height=500)


def community_role_figure(role_table: pd.DataFrame, community: int) -> go.Figure | None:
    """Build the selected Louvain community's observed role-composition chart."""
    if role_table.empty or "community" not in role_table.columns:
        return None
    row = role_table[role_table["community"] == community]
    if row.empty:
        return None

    mapping = {
        "TOP": "Top",
        "JUNGLE": "Jungle",
        "MIDDLE": "Mid",
        "BOTTOM": "ADC",
        "UTILITY": "Support",
    }
    values = []
    labels = []
    for source_col, label in mapping.items():
        if source_col in row.columns:
            labels.append(label)
            values.append(float(row[source_col].iloc[0]))

    fig = go.Figure(
        go.Bar(
            x=labels,
            y=values,
            marker_color=["#8CA6BF", "#6F91AF", "#D0AA55", "#C58B63", "#8F77A8"],
            hovertemplate="%{x}: %{y:.1f}%<extra></extra>",
        )
    )
    fig.update_layout(
        title=f"Community C{community}: observed role composition",
        xaxis_title="Role",
        yaxis_title="Share of appearances (%)",
        yaxis_range=[0, max(100, max(values) * 1.12 if values else 100)],
    )
    return style_plot(fig, height=390)


def render_overview() -> None:
    """Render the project's scale, three questions, and final high-level takeaways."""
    st.subheader("Project overview")

    cols = st.columns(4)
    cols[0].metric("Unique matches", f"{PROJECT_MATCHES:,}")
    cols[1].metric("Participant rows", f"{PROJECT_PARTICIPANTS:,}")
    cols[2].metric("Regions", "NA · KR · EU")
    cols[3].metric("Tracked players", f"{TRACKED_PLAYERS:,}")

    st.markdown("#### Three complementary questions")
    cards = st.columns(3)
    cards[0].markdown(
        """
        <div class="problem-card">
          <h4>1 · Temporal behavior</h4>
          <b>Do session depth, recent volume, or rapid post-loss requeue predict a worse next match?</b>
          <p class="small-note">Within-player inference + chronological decision trees.</p>
          <p><b>Takeaway:</b> effects were small and inconsistent; behavioral features added only limited predictive value.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    cards[1].markdown(
        """
        <div class="problem-card">
          <h4>2 · Champion pairings</h4>
          <b>Which champion pairs appear together more than expected, and how do those pairs perform?</b>
          <p class="small-note">Raw co-picks + log₂(lift) + descriptive win surplus.</p>
          <p><b>Takeaway:</b> popularity, unusual co-selection, and pair performance are distinct properties.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    cards[2].markdown(
        """
        <div class="problem-card">
          <h4>3 · Champion network</h4>
          <b>What communities, central champions, and recurring groups emerge from the full co-selection network?</b>
          <p class="small-note">Louvain + PageRank + cliques + clustering comparisons.</p>
          <p><b>Takeaway:</b> graph methods reveal interpretable relational structure beyond isolated pairs.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown("#### Demo readiness")
    q1_ready = file_ready(Q1_TABLES / "key_results_for_report.csv")
    q2_ready = file_ready(Q2_TABLES / "pair_stats.csv")
    q3_ready = file_ready(Q3_TABLES / "centrality.csv")
    status = st.columns(3)
    status[0].markdown(
        f"Problem 1: <span class=\"{'status-ok' if q1_ready else 'status-missing'}\">"
        f"{'ready' if q1_ready else 'not generated'}</span>",
        unsafe_allow_html=True,
    )
    status[1].markdown(
        f"Problem 2: <span class=\"{'status-ok' if q2_ready else 'status-missing'}\">"
        f"{'ready' if q2_ready else 'not generated'}</span>",
        unsafe_allow_html=True,
    )
    status[2].markdown(
        f"Problem 3: <span class=\"{'status-ok' if q3_ready else 'status-missing'}\">"
        f"{'ready' if q3_ready else 'not generated'}</span>",
        unsafe_allow_html=True,
    )

    if not (q1_ready and q2_ready and q3_ready):
        st.info(
            "The dashboard intentionally reads generated analysis outputs instead "
            "of recomputing the full project. Run the pipeline once before the demo."
        )
        st.code("python code/run_project.py", language="bash")


def render_q1() -> None:
    """Render Problem 1 metrics, adjusted effects, prediction, and interpretation."""
    st.subheader("Problem 1 · Temporal Behavior & Next-Match Performance")
    st.caption(
        "Question: how are recent volume, session depth, and post-loss requeue timing "
        "associated with performance in the following Ranked Solo/Duo match?"
    )

    key_path = Q1_TABLES / "key_results_for_report.csv"
    effects_path = Q1_TABLES / "behavior_effects.csv"
    if not file_ready(key_path) or not file_ready(effects_path):
        missing_results_message("Problem 1", "python code/run_project.py q1 --strict-reference")
        return

    key = read_csv(key_path)
    effects = read_csv(effects_path)

    combined_auc = key_metric(key, "Combined tree test ROC-AUC")
    history_auc = key_metric(key, "History tree test ROC-AUC")
    delta_auc = key_metric(key, "Combined - history AUC")
    holm_terms = key_metric(key, "Holm-significant robustness terms")

    cols = st.columns(4)
    cols[0].metric("Primary targets", format_integer(key_metric(key, "Primary target observations") or 0))
    cols[1].metric("Combined test AUC", format_decimal(combined_auc or np.nan))
    cols[2].metric(
        "Behavioral AUC gain",
        f"+{format_decimal(delta_auc or 0)}",
        help="Combined-tree ROC-AUC minus history-only tree ROC-AUC.",
    )
    cols[3].metric("Holm-significant robustness terms", format_integer(holm_terms or 0))

    st.info(
        "Main message: the data do not support a simple universal story that deeper "
        "sessions or very fast post-loss requeues reliably reduce next-match win probability."
    )

    controls = st.columns([1, 1, 2])
    hypothesis = controls[0].selectbox(
        "Behavioral question",
        ["Session depth", "Post-loss requeue", "Recent ranked volume"],
        key="q1_hypothesis",
    )
    region = controls[1].selectbox(
        "Region",
        ["ALL", "NA", "KR", "EU"],
        key="q1_region",
    )

    primary = primary_effects(effects, hypothesis)
    if primary.empty:
        st.warning("Primary adjusted coefficients were not found in behavior_effects.csv.")
    else:
        st.plotly_chart(
            q1_effect_figure(primary, hypothesis, region),
            use_container_width=True,
            config={"displayModeBar": False},
        )

    left, right = st.columns([1.05, 0.95])
    with left:
        prediction_figure = Q1_FIGURES / "figure_3_prediction_evaluation.png"
        if file_ready(prediction_figure):
            st.image(
                report_image_bytes(prediction_figure),
                caption="Held-out prediction: ROC curves and combined-tree confusion matrix.",
                use_container_width=True,
            )
        else:
            st.markdown("##### Predictive result")
            st.metric("History-only AUC", format_decimal(history_auc or np.nan))
            st.metric("Combined AUC", format_decimal(combined_auc or np.nan))
    with right:
        st.markdown("##### Why this matters")
        st.markdown(
            """
            - Predictors were built **strictly before the target match** to avoid leakage.
            - The main inferential comparison is **within player**, reducing confounding by stable player skill.
            - Uncertainty was clustered by both **player** and **physical match**.
            - The result is **observational**, so it should not be interpreted as a causal test of psychological tilt or fatigue.
            """
        )


def render_q2() -> None:
    """Render the interactive champion-pair explorer for Problem 2."""
    st.subheader("Problem 2 · Champion Pairings & Combo Performance")
    st.caption(
        "Raw popularity, above-expected co-selection, and descriptive pair performance "
        "are deliberately treated as separate quantities."
    )

    pair_path = Q2_TABLES / "pair_stats.csv"
    champion_path = Q2_TABLES / "champion_stats.csv"
    if not file_ready(pair_path) or not file_ready(champion_path):
        missing_results_message("Problem 2", "python code/run_project.py q2")
        return

    pairs = read_csv(pair_path)
    champions = read_csv(champion_path)
    names = champions.sort_values("appearances", ascending=False)["champion_name"].dropna().tolist()

    selected = st.selectbox(
        "Select a champion",
        names,
        index=0,
        key="q2_champion",
    )
    champion_row = champions[champions["champion_name"] == selected].iloc[0]
    selected_pairs = pairs_for_champion(pairs, selected)

    supported = selected_pairs[selected_pairs["games_together"] >= MIN_PAIR_GAMES]
    high_support = selected_pairs[selected_pairs["games_together"] >= MIN_PERFORMANCE_GAMES]

    cols = st.columns(4)
    cols[0].metric("Appearances", f"{int(champion_row['appearances']):,}")
    cols[1].metric("Pick rate", f"{100 * float(champion_row['pick_rate']):.2f}%")
    cols[2].metric("Win rate", f"{100 * float(champion_row['win_rate']):.2f}%")
    cols[3].metric("Supported partners", f"{len(supported):,}")

    if supported.empty:
        st.info(f"No {selected} pairings meet the {MIN_PAIR_GAMES:,}-game support threshold.")
        return

    strongest = supported.nlargest(1, "association").iloc[0]
    common = selected_pairs.nlargest(1, "games_together").iloc[0]
    performance = (
        high_support.nlargest(1, "win_surplus_pp").iloc[0]
        if not high_support.empty
        else None
    )

    highlights = st.columns(3)
    highlights[0].metric(
        "Most common partner",
        common["partner"],
        f"{int(common['games_together']):,} games",
    )
    highlights[1].metric(
        "Strongest normalized partner",
        strongest["partner"],
        f"log₂(lift) {float(strongest['association']):.2f}",
    )
    if performance is not None:
        highlights[2].metric(
            "Largest high-support win surplus",
            performance["partner"],
            f"{float(performance['win_surplus_pp']):+.2f} pp",
        )

    st.plotly_chart(
        q2_scatter(selected_pairs, selected),
        use_container_width=True,
        config={"displayModeBar": False},
    )

    sort_label = st.radio(
        "Rank partner table by",
        ["Normalized association", "Games together", "Win surplus"],
        horizontal=True,
        key="q2_sort",
    )
    sort_map = {
        "Normalized association": "association",
        "Games together": "games_together",
        "Win surplus": "win_surplus_pp",
    }
    table = selected_pairs.sort_values(sort_map[sort_label], ascending=False).head(20)
    table = table[
        [
            "partner",
            "games_together",
            "association",
            "pair_win_rate",
            "win_surplus_pp",
        ]
    ].rename(
        columns={
            "partner": "Partner",
            "games_together": "Games together",
            "association": "log₂(lift)",
            "pair_win_rate": "Pair win rate",
            "win_surplus_pp": "Win surplus (pp)",
        }
    )
    st.dataframe(
        table.style.format(
            {
                "Games together": "{:,.0f}",
                "log₂(lift)": "{:.3f}",
                "Pair win rate": "{:.3f}",
                "Win surplus (pp)": "{:+.3f}",
            }
        ),
        use_container_width=True,
        hide_index=True,
    )

    st.info(
        "Interpretation: a high log₂(lift) means a pair appears together more often "
        "than expected from their individual popularity. Win surplus is descriptive, "
        "not a causal estimate of champion synergy."
    )


def render_q3() -> None:
    """Render community, centrality, neighbor, role, and clique views for Problem 3."""
    st.subheader("Problem 3 · Champion Network Structure & Team-Composition Communities")
    st.caption(
        "Problem 3 asks what becomes visible when the pair relationships from Problem 2 "
        "are analyzed as one weighted network."
    )

    centrality_path = Q3_TABLES / "centrality.csv"
    communities_path = Q3_TABLES / "louvain_communities.csv"
    role_path = Q3_TABLES / "community_role_percent.csv"
    cliques_path = Q3_TABLES / "maximal_cliques.csv"
    pair_path = Q2_TABLES / "pair_stats.csv"

    required = [centrality_path, communities_path, role_path, pair_path]
    if not all(file_ready(path) for path in required):
        missing_results_message(
            "Problem 3",
            "python code/run_project.py q2\npython code/run_project.py q3",
        )
        return

    centrality = read_csv(centrality_path)
    communities = read_csv(communities_path)
    role_table = read_csv(role_path)
    pairs = read_csv(pair_path)
    cliques = read_csv(cliques_path) if file_ready(cliques_path) else pd.DataFrame()

    merged = centrality.merge(
        communities[["champion_id", "community"]],
        on="champion_id",
        how="left",
    )
    names = merged.sort_values("pagerank_association", ascending=False)["champion_name"].tolist()
    selected = st.selectbox("Select a champion", names, key="q3_champion")
    row = merged[merged["champion_name"] == selected].iloc[0]
    community = int(row["community"])

    selected_pairs = pairs_for_champion(pairs, selected)
    neighbors = selected_pairs[
        (selected_pairs["games_together"] >= MIN_PAIR_GAMES)
        & (selected_pairs["association"] > 0)
    ].sort_values("association", ascending=False)

    cols = st.columns(4)
    cols[0].metric("Louvain community", f"C{community}" if community > 0 else "Outside core")
    cols[1].metric("Association PageRank", f"{float(row['pagerank_association']):.5f}")
    cols[2].metric("Association weighted degree", f"{float(row['degree_association']):.2f}")
    cols[3].metric("Positive supported neighbors", f"{len(neighbors):,}")

    left, right = st.columns([1.1, 0.9])
    with left:
        st.plotly_chart(
            pagerank_figure(centrality, selected),
            use_container_width=True,
            config={"displayModeBar": False},
        )
    with right:
        role_fig = community_role_figure(role_table, community)
        if role_fig is not None:
            st.plotly_chart(
                role_fig,
                use_container_width=True,
                config={"displayModeBar": False},
            )

    st.markdown("##### Strongest normalized network neighbors")
    if neighbors.empty:
        st.write("No supported positive-association neighbors were found.")
    else:
        neighbor_table = neighbors.head(12)[
            ["partner", "games_together", "association", "win_surplus_pp"]
        ].rename(
            columns={
                "partner": "Neighbor",
                "games_together": "Games together",
                "association": "log₂(lift)",
                "win_surplus_pp": "Win surplus (pp)",
            }
        )
        st.dataframe(
            neighbor_table.style.format(
                {
                    "Games together": "{:,.0f}",
                    "log₂(lift)": "{:.3f}",
                    "Win surplus (pp)": "{:+.3f}",
                }
            ),
            use_container_width=True,
            hide_index=True,
        )

    if not cliques.empty and "champions" in cliques.columns:
        member_mask = cliques["champions"].astype(str).apply(
            lambda value: selected in [x.strip() for x in value.split("|")]
        )
        selected_cliques = cliques[member_mask].head(10)
        st.markdown("##### Strong cliques containing this champion")
        if selected_cliques.empty:
            st.write("No strong maximal clique contains the selected champion.")
        else:
            show = selected_cliques[
                ["champions", "size", "mean_association", "minimum_games", "mean_win_surplus_pp"]
            ].rename(
                columns={
                    "champions": "Champions",
                    "size": "Clique size",
                    "mean_association": "Mean association",
                    "minimum_games": "Minimum edge games",
                    "mean_win_surplus_pp": "Mean win surplus (pp)",
                }
            )
            st.dataframe(
                show.style.format(
                    {
                        "Mean association": "{:.3f}",
                        "Minimum edge games": "{:,.0f}",
                        "Mean win surplus (pp)": "{:+.3f}",
                    }
                ),
                use_container_width=True,
                hide_index=True,
            )

    network_figure = Q3_FIGURES / "figure_8_louvain_community_network.png"
    if file_ready(network_figure):
        with st.expander("Show the full report network figure"):
            st.image(report_image_bytes(network_figure), use_container_width=True)

    st.info(
        "Main message: graph methods preserve pair relationships directly. The resulting "
        "communities and centrality patterns are therefore more interpretable than forcing "
        "the same structure into a small number of Euclidean clusters."
    )


def main() -> None:
    """Build the four-tab presentation dashboard from validated analysis outputs."""
    st.markdown(
        """
        <div class="hero">
          <div class="hero-title">Finding the Needle in Ranked Play</div>
          <div class="hero-sub">Behavioral and Strategic Patterns in League of Legends</div>
          <div class="small-note">Interactive results explorer · Data Science 67978</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    with st.sidebar:
        st.markdown("### Demo guide")
        st.write(
            "This app reads the final generated tables and figures. "
            "It does not retrain or rescan the full dataset."
        )
        st.markdown("**Recommended live path**")
        st.markdown(
            "1. Overview\n"
            "2. Problem 1 result\n"
            "3. Pick a champion in Problem 2\n"
            "4. Follow that champion into Problem 3"
        )
        st.divider()
        st.caption("Generate results first:")
        st.code("python code/run_project.py", language="bash")
        st.caption("Then launch:")
        st.code("streamlit run demo/app.py", language="bash")

    overview_tab, q1_tab, q2_tab, q3_tab = st.tabs(
        [
            "Overview",
            "1 · Temporal Behavior",
            "2 · Champion Pairings",
            "3 · Champion Network",
        ]
    )

    with overview_tab:
        render_overview()
    with q1_tab:
        render_q1()
    with q2_tab:
        render_q2()
    with q3_tab:
        render_q3()

    st.divider()
    st.caption(
        "All displayed results are observational. The demo is a presentation layer over "
        "the reproducible analysis pipeline, not a separate modeling workflow."
    )


if __name__ == "__main__":
    main()
